[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Facebook"
  pageRef = "facebook"
  pre = "facebook"
  weight = 20

[[main]]
  name = "YouTube"
  pageRef = "youtube"
  pre = "youtube"
  weight = 21

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[footer]]
  name = "Facebook"
  pageRef = "facebook"
  weight = 10

[[footer]]
  name = "YouTube"
  pageRef = "youtube"
  weight = 11
