name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.164.0'

      - name: Build Hugo Site
        run: hugo

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '24'

      - name: Index with Pagefind
        run: npx pagefind --site public


      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          command: pages deploy public -project-name blog
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: deploying to surge
        uses: mahmoudgalalz/surge-action@v0.1.5
        with:
          domain: 'myblog-prohllad.surge.sh'
          path: './public'
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main